name: inklewriter
apiVersion: v2
appVersion: "1.16.0"
description: Inklewriter is a simple-to-use web application for Interactive Fiction writing
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.4.1
type: application
version: 0.1.0
