version: '2'

volumes:
  inkledb:

networks:
  inklenet:

services:

  db:
    env_file: .env
    image: postgres
    volumes:
      - inkledb:/opt
    networks:
      - inklenet
      
  app:
    env_file: .env
    image: albancrommer/inklewriter:latest
    ports:
      - "3000:3000"
    networks:
      - inklenet
    depends_on:
      - db
  

      
